### ISSUE TITLE
Recent updates need to be pushed to npm registry

### ISSUE THREAD

**Issue by 01** [OfficeDev/BotBuilder-MicrosoftTeams-node#11]
The recent changes are needed specifically ms-rest-js to @azure/ms-rest-js change since many of the other botbuilder-libraries have updated to that library. If both modules are present there are breaking type conflictions.

**Comment by robin-liao** [comment]
I believe we've already done so. Actually in my design, there's not only no dependency of "ms-rest-js", but also no direct dependency of "@azure/ms-rest-js", while we only rely on the indirect dependency where `@azure/ms-rest-js` comes from the package definition of botbuilder. 

For example, there's no any definition of ms-rest-js or @azure/ms-rest-js in package.json, and also by checking package-lock.json you can find the `@azure/ms-rest-js ` dependency is from `botframework-connector`.

**Comment by 01** [comment]
@robin-liao  you are correct my apologies since the last publish was 2 months ago and no version change and I only just now had the issue I incorrectly assumed it hadnt been pushed to the registry
