### ISSUE TITLE
Ability to obtain member list of team

### ISSUE THREAD

**Issue by Sn00z3r** [OfficeDev/BotBuilder-MicrosoftTeams-node#18]
Is there a method to obtain the member list of a team, can't seem to find it in the documentation or the source code. Might have glanced over it :).

Best regards

**Comment by clearab** [comment]
You can find an example of how to do this here: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/blob/master/samples/teams-bot/src/bot.ts#L63
