### ISSUE TITLE
Samples don't build out of the box

### ISSUE THREAD

**Issue by navzam** [OfficeDev/BotBuilder-MicrosoftTeams-node#5]
There are no instructions on running the samples, so I tried to do this:

```bash
cd ./samples/teams-bot/
npm i
npx tsc
```

The build fails with the following output:

```
src/app.ts:10:24 - error TS2307: Cannot find module 'botbuilder-teams'.

10 import * as teams from 'botbuilder-teams';
                          ~~~~~~~~~~~~~~~~~~

src/bot.ts:5:24 - error TS2307: Cannot find module 'botbuilder-teams'.

5 import * as teams from 'botbuilder-teams';
                         ~~~~~~~~~~~~~~~~~~

Found 2 errors.
```

I assume this is because the samples refer to `botbuilder-teams` locally:

https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-node/blob/87e925af584670080677cb09f20d48f4de8797cb/samples/teams-bot/package.json#L12

which is not built when you clone the repo. If I go into the local package and build it:

```
cd ../../botbuilder-teams-js/
npm i
npx tsc
```

and then re-run `npm i` in the sample, then it builds successfully.

I think there are 2 issues here:
1) There are no instructions on how to run the samples.
2) The samples use the local `botbuilder-teams` module instead of the one from npm, meaning a) the developer has to build the module themselves, and b) the sample code may not work against the latest npm package. (This is currently the case - sample code doesn't work against the published `4.0.0-beta1`)

**Comment by robin-liao** [comment]
@navzam for issue 2 it's on purpose. The latest version of library code in the repo isn't the latest published version. Usually we will wait for several new (small) features ready and publish next NPM release in a batch. So, in order to make sure the samples can always use the latest (unpublished) features, we refer them to local library code and bundle them within the same repo.

For issue 1, I'll make up documentation later. Thanks for your try!

**Comment by navzam** [comment]
@robin-liao thanks for the quick response! I still think the samples would be most useful if they pointed to the npm packages, since most developers will be using a published package, not the master branch. But happy to see what others in the community think.

**Comment by clearab** [comment]
Hi - the samples in this repo are specific to the version of the code inside the repo. If you'd like to try some of our samples that point at the NPM packages, have a look at https://aka.ms/teamsappsamples. There's quite a few of them there.

**Comment by navzam** [comment]
Thanks @clearab. I didn't see any Node samples there that use v4
